baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mwaddoups.io/" # the base hostname & protocol for your site, e.g. http://example.com

site.locale: "en-GB"
atom_feed:
  hide: true
title: Blog | Mark
name: "Mark Waddoups"
email: mwaddoups@gmail.com
site.description: >- 
  Personal blog for Mark Waddoups.
repository: mwaddoups/blog
paginate: 5

author:
  name: "Mark Waddoups"
  avatar: "/assets/images/bio-photo.jpg"
  bio: >-
    Co-founder of Bayesian Shift and impactful data scientist. My personal blog on
    various topics that I find interesting. 
  location: Bristol, UK

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true


# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
